### ISSUE TITLE
User defined types not fully implemented (how to use ConstDataType ?)

### ISSUE THREAD

**Issue by antoine-de** [Metaswitch/cassandra-rs#36]
Hi,

sorry for my noob question, but I wanted to do a bulk insert in cassandra with a list of UserDefinedType and never managed to do it :confused: 

I tried to get a handle on a udt with the [schema meta](https://github.com/Metaswitch/cassandra-rs/blob/master/src/cassandra/schema/keyspace_meta.rs#L67) but the return value is a [`ConstDataType`](https://github.com/Metaswitch/cassandra-rs/blob/master/src/cassandra/data_type.rs#L36) and I don't know what to do with it :roll_eyes: 

I wanted to use [`new_user_type`](https://github.com/Metaswitch/cassandra-rs/blob/master/src/cassandra/data_type.rs#L60) but it's for [`DataType`](https://github.com/Metaswitch/cassandra-rs/blob/master/src/cassandra/data_type.rs#L34) and I don't see an easy want to coerce a `ConstDataType` to a `DataType` (and it seems normal not to).

What is the right way to bind a list of udt in a statement ?

**Comment by kw217** [comment]
Hi @antoine-de - it's not a noob question, you have stumbled across part of the driver which is not yet fully implemented!

Unfortunately: `Value::get_user_type` correctly gets a `UserTypeIterator`, but that iterator wraps only [`cass_iterator_get_user_type`](https://docs.datastax.com/en/developer/cpp-driver/2.8/api/struct.CassIterator/#function-cass_iterator_get_user_type) which gives metadata info, rather than `cass_iterator_get_user_type_field_name` and `cass_iterator_get_user_type_value` which would give the actual content. Similarly as you spotted constructing a `UserType` in the first place is challenging.

I'd be happy to accept a patch if you want to attempt it - you just need to fix up the declaration of `UserTypeIterator` in `iterator.rs` to have a sensible `Item` type and `next` definition. Resurrecting the `examples/disabled/udt.rs` by promoting it to `examples/udt.rs` and getting it to run successfully would be a good test. You'll need to make some minor changes since it's a while since that test compiled - e.g., use `cassandra_cpp` rather than `cassandra`, and some methods take fewer parameters now.

**Comment by kw217** [comment]
This is resolved by #49.

**Comment by antoine-de** [comment]
great! sorry I stoped working on this, and forgot this issue.

great work!
